# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.box_check_update = true

    config.vm.network "forwarded_port", guest:8000, host:8111
    config.vm.network "forwarded_port", guest:5432, host:65432

    config.ssh.insert_key = true
    config.ssh.forward_agent = true

    config.vm.synced_folder ".", "/usr/local/apps/marineplanner-core"

    config.vm.provision "shell" do |s|
      s.path = "scripts/vagrant_provision0.sh"
      s.args = ['xenial', '3.5.0', '9.5']
    end

    ### INSTALL ENVIRONMENT AND SETUP DB
    # Args: Project Name, Application name, Database name
    config.vm.provision "shell" do |s|
      s.path = "scripts/vagrant_provision.sh"
      s.args = ['marineplanner-core', 'marineplanner', 'marineplanner', '/usr/local/apps/marineplanner-core/apps/landmapper/landmapper']
      s.privileged = "false"
    end

    ### INSERT MODULE PROVISION FILES HERE ###
    config.vm.provision "shell" do |s|
      s.path = "apps/mp-accounts/scripts/vagrant_provision.sh"
      s.args = "marineplanner-core"
      s.privileged = "false"
    end
    config.vm.provision "shell" do |s|
      s.path = "apps/mp-visualize/scripts/vagrant_provision.sh"
      s.args = "marineplanner-core"
      s.privileged = "false"
    end
    ### END MODULE PROVISION FILES ###

    # If a 'Vagrantfile.local' file exists, import any configuration settings
    # defined there into here. Vagrantfile.local is ignored in version control,
    # so this can be used to add configuration specific to this computer.

    #if File.exist? "Vagrantfile.local"
        #instance_eval File.read("Vagrantfile.local"), "Vagrantfile.local"
    #end

    config.vm.provision "shell" do |s|
      s.path = "scripts/vagrant_finish_provision.sh"
      s.args = ['marineplanner-core', 'marineplanner']
      s.privileged = "false"
    end
end
