# Generated by Django 4.2b1 on 2024-02-22 18:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='COA',
            fields=[
                ('huc12', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('coa_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('coa_id', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('ecoregion', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('profile_link', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='HUC COA Geometry')),
            ],
        ),
    ]
