# Generated by Django 4.2.7 on 2024-07-31 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240731_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupage',
            name='content',
        ),
    ]
