# Generated by Django 4.2.7 on 2024-07-31 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_menupage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menupage',
            old_name='contentTinyMCE',
            new_name='content',
        ),
    ]
